
-- ============================================================================
-- Seed data for melodymart_db (JPA Unified Database)
-- ============================================================================


-- Set default values for JPA dynamic fields
ALTER TABLE `products` ALTER COLUMN `is_deleted` SET DEFAULT 0;

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE `product_specifications`;
TRUNCATE TABLE `product_images`;
TRUNCATE TABLE `products`;
TRUNCATE TABLE `sub_categories`;
TRUNCATE TABLE `categories`;
TRUNCATE TABLE `brands`;
SET FOREIGN_KEY_CHECKS = 1;

-- 1. Seed brands
INSERT INTO `brands` (`id`, `name`, `slug`, `description`, `logo_url`, `created_at`, `updated_at`) VALUES (1, 'Yamaha', 'yamaha', 'Global leader in musical instrument production and digital audio systems.', 'https://cdn.melodymart.com/brands/yamaha.png', NOW(), NOW());
INSERT INTO `brands` (`id`, `name`, `slug`, `description`, `logo_url`, `created_at`, `updated_at`) VALUES (2, 'Fender', 'fender', 'Legendary manufacturer of acoustic, electric, and bass guitars.', 'https://cdn.melodymart.com/brands/fender.png', NOW(), NOW());
INSERT INTO `brands` (`id`, `name`, `slug`, `description`, `logo_url`, `created_at`, `updated_at`) VALUES (3, 'Roland', 'roland', 'Pioneering electronic instruments manufacturer, synthesizer developer, and digital drums producer.', 'https://cdn.melodymart.com/brands/roland.png', NOW(), NOW());
INSERT INTO `brands` (`id`, `name`, `slug`, `description`, `logo_url`, `created_at`, `updated_at`) VALUES (4, 'Shure', 'shure', 'Industry-standard microphones and studio audio monitoring gear.', 'https://cdn.melodymart.com/brands/shure.png', NOW(), NOW());
INSERT INTO `brands` (`id`, `name`, `slug`, `description`, `logo_url`, `created_at`, `updated_at`) VALUES (5, 'Focusrite', 'focusrite', 'Renowned manufacturer of high-quality USB audio recording interfaces.', 'https://cdn.melodymart.com/brands/focusrite.png', NOW(), NOW());

-- 2. Seed categories
INSERT INTO `categories` (`id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (1, 'String Instruments', 'string-instruments', 'Instruments containing strings that vibrate to produce sound (guitars, violins, cellos).', NOW(), NOW());
INSERT INTO `categories` (`id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (2, 'Keyboard Instruments', 'keyboard-instruments', 'Instruments played using a musical keyboard interface (pianos, portable keys, stage keys).', NOW(), NOW());
INSERT INTO `categories` (`id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (3, 'Percussion Instruments', 'percussion-instruments', 'Instruments struck to make rhythmic or melodic sounds (drum kits, tablas, cajons).', NOW(), NOW());
INSERT INTO `categories` (`id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (4, 'Wind Instruments', 'wind-instruments', 'Instruments operated by blowing air into a resonator (flutes, trumpets, saxophones).', NOW(), NOW());

-- 3. Seed sub_categories
INSERT INTO `sub_categories` (`id`, `category_id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (1, 1, 'Guitar', 'guitar', 'Acoustic, semi-acoustic, and electric guitars.', NOW(), NOW());
INSERT INTO `sub_categories` (`id`, `category_id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (2, 1, 'Violin', 'violin', 'Classical and electric violins.', NOW(), NOW());
INSERT INTO `sub_categories` (`id`, `category_id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (3, 1, 'Ukulele', 'ukulele', 'Four-string Hawaiian chordophones.', NOW(), NOW());
INSERT INTO `sub_categories` (`id`, `category_id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (4, 1, 'Bass Guitar', 'bass-guitar', 'Low-pitched electric or acoustic guitars.', NOW(), NOW());
INSERT INTO `sub_categories` (`id`, `category_id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (5, 1, 'Cello', 'cello', 'Large bowed orchestral string instruments.', NOW(), NOW());
INSERT INTO `sub_categories` (`id`, `category_id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (6, 2, 'Digital Piano', 'digital-piano', 'Electronic keyboard instruments designed to emulate acoustic pianos.', NOW(), NOW());
INSERT INTO `sub_categories` (`id`, `category_id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (7, 2, 'Grand Piano', 'grand-piano', 'Horizontal acoustic pianos with premium strings and action.', NOW(), NOW());
INSERT INTO `sub_categories` (`id`, `category_id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (8, 2, 'Upright Piano', 'upright-piano', 'Space-efficient vertical acoustic pianos.', NOW(), NOW());
INSERT INTO `sub_categories` (`id`, `category_id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (9, 2, 'Stage Piano', 'stage-piano', 'High-end performance keyboards for stage and studio.', NOW(), NOW());
INSERT INTO `sub_categories` (`id`, `category_id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (10, 2, 'Portable Keyboard', 'portable-keyboard', 'Lightweight keyboards with built-in speakers.', NOW(), NOW());
INSERT INTO `sub_categories` (`id`, `category_id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (11, 2, 'Arranger Keyboard', 'arranger-keyboard', 'Keyboards with automated backing accompaniment features.', NOW(), NOW());
INSERT INTO `sub_categories` (`id`, `category_id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (12, 3, 'Drum Kit', 'drum-kit', 'Acoustic and electronic multi-drum sets.', NOW(), NOW());
INSERT INTO `sub_categories` (`id`, `category_id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (13, 3, 'Tabla', 'tabla', 'Traditional Indian twin hand-drums.', NOW(), NOW());
INSERT INTO `sub_categories` (`id`, `category_id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (14, 3, 'Conga', 'conga', 'Tall, narrow, single-headed African-Cuban drums.', NOW(), NOW());
INSERT INTO `sub_categories` (`id`, `category_id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (15, 3, 'Bongo', 'bongo', 'Small Afro-Cuban paired hand-drums.', NOW(), NOW());
INSERT INTO `sub_categories` (`id`, `category_id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (16, 3, 'Cajon', 'cajon', 'Box-shaped percussion instruments originating from Peru.', NOW(), NOW());
INSERT INTO `sub_categories` (`id`, `category_id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (17, 4, 'Flute', 'flute', 'Woodwind instruments producing sound from flow of air.', NOW(), NOW());
INSERT INTO `sub_categories` (`id`, `category_id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (18, 4, 'Trumpet', 'trumpet', 'High-register brass instruments with three valves.', NOW(), NOW());
INSERT INTO `sub_categories` (`id`, `category_id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (19, 4, 'Clarinet', 'clarinet', 'Single-reed woodwind instruments with cylindrical bores.', NOW(), NOW());
INSERT INTO `sub_categories` (`id`, `category_id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (20, 4, 'Saxophone', 'saxophone', 'Single-reed brass woodwind instruments used widely in jazz.', NOW(), NOW());
INSERT INTO `sub_categories` (`id`, `category_id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (21, 4, 'Harmonica', 'harmonica', 'Free-reed pocket wind instruments.', NOW(), NOW());

-- 4. Seed products
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (1, 'Fiddle', 'fiddle', 2, 1, 1, 'Premium Fiddle crafted for artists and performers.', 849.99, 10, 25, 4.82, 142, 24, '0144502513', 'FEN-PLY-STR-OW3', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (6, 'Lute', 'lute', 2, 1, 1, 'Premium Lute crafted for artists and performers.', 799, 0, 14, 4.65, 38, 12, 'PM-1-STD', 'FEN-PAR-PM1-NAT', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (8, 'Erhu', 'erhu', 1, 1, 1, 'Premium Erhu crafted for artists and performers.', 229.99, 0, 45, 4.8, 421, 24, 'FG800', 'YAM-FG800-NT', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (9, 'Santoor', 'santoor', 1, 1, 2, 'Premium Santoor crafted for artists and performers.', 1799, 8, 8, 4.88, 19, 36, 'SV-250', 'YAM-SV250-BR', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (10, 'Tanpura', 'tanpura', 2, 1, 3, 'Premium Tanpura crafted for artists and performers.', 299.99, 10, 12, 4.54, 22, 12, 'CT-54', 'FEN-CT54-MND', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (11, 'Veena', 'veena', 2, 1, 3, 'Premium Veena crafted for artists and performers.', 89.99, 0, 95, 4.7, 114, 12, 'SEASIDE-SOP', 'FEN-SEA-SOP-UK', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (12, 'Sarod', 'sarod', 1, 1, 4, 'Premium Sarod crafted for artists and performers.', 399.99, 0, 18, 4.76, 88, 24, 'TRBX304', 'YAM-TRBX304-CAR', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (14, 'Mandolin', 'mandolin', 1, 1, 5, 'Premium Mandolin crafted for artists and performers.', 2499.99, 10, 4, 4.93, 15, 36, 'SVC-110', 'YAM-SVC110-CEL', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (2, 'Stage Piano', 'stage-piano', 1, 2, 6, 'Premium Stage Piano crafted for artists and performers.', 699.99, 0, 40, 4.75, 98, 36, 'P125B', 'YAM-P125B-88', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (16, 'Spinet Piano', 'spinet-piano', 3, 2, 7, 'Premium Spinet Piano crafted for artists and performers.', 5499, 0, 3, 4.96, 8, 60, 'GP-6-PE', 'ROL-GP6-GRAND', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (17, 'concert Organ', 'concert-organ', 1, 2, 8, 'Premium concert Organ crafted for artists and performers.', 4899, 0, 2, 4.9, 14, 120, 'b3-PE', 'YAM-B3-UPRIGHT', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (19, 'Arranger Keyboard', 'arranger-keyboard', 1, 2, 10, 'Premium Arranger Keyboard crafted for artists and performers.', 199.99, 0, 75, 4.68, 312, 24, 'PSR-E373', 'YAM-PSRE373-KB', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (20, 'Electric Keyboard', 'electric-keyboard', 3, 2, 10, 'Premium Electric Keyboard crafted for artists and performers.', 329.99, 10, 34, 4.62, 56, 24, 'GO-61K', 'ROL-GO61K-KB', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (21, 'Melodica', 'melodica', 1, 2, 11, 'Premium Melodica crafted for artists and performers.', 2199, 0, 6, 4.92, 28, 36, 'PSR-SX900', 'YAM-SX900-ARR', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (23, 'Synthesizer', 'synthesizer', 3, 2, 9, 'Premium Synthesizer crafted for artists and performers.', 1999.99, 0, 5, 4.89, 22, 24, 'FANTOM-08', 'ROL-FAN08-WS', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (24, 'Vibraphone', 'vibraphone', 1, 3, 12, 'Premium Vibraphone crafted for artists and performers.', 679.99, 0, 10, 4.84, 45, 24, 'SBP2F50', 'YAM-SCB-BIRCH', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (25, 'Marimba', 'marimba', 1, 3, 12, 'Premium Marimba crafted for artists and performers.', 499.99, 8, 20, 4.68, 89, 24, 'RYDEEN-5PC', 'YAM-RYD-5PC-RD', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (26, 'Xylophone', 'xylophone', 3, 3, 12, 'Premium Xylophone crafted for artists and performers.', 799.99, 0, 25, 4.7, 37, 12, 'TD-07DMK', 'ROL-TD07DMK-ED', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (27, 'Cowbell', 'cowbell', 1, 3, 14, 'Premium Cowbell crafted for artists and performers.', 449.99, 10, 8, 4.73, 16, 24, 'YCG-1112', 'YAM-WCG-PAIR', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (28, 'Claves', 'claves', 3, 3, 12, 'Premium Claves crafted for artists and performers.', 1199.99, 0, 12, 4.94, 48, 24, 'SPD-SX-PRO', 'ROL-SPDSXP-SP', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (30, 'Maracas', 'maracas', 3, 3, 12, 'Premium Maracas crafted for artists and performers.', 999.99, 0, 6, 4.81, 23, 24, 'HPD-20', 'ROL-HPD20-HP', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (31, 'Triangle', 'triangle', 1, 3, 16, 'Premium Triangle crafted for artists and performers.', 129.99, 10, 40, 4.6, 52, 12, 'CJ-YAM', 'YAM-SNARE-CAJ', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (32, 'Tambourine', 'tambourine', 3, 3, 16, 'Premium Tambourine crafted for artists and performers.', 399.99, 0, 11, 4.74, 18, 24, 'EC-10', 'ROL-EC10-CAJ', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (34, 'Recorder', 'recorder', 1, 4, 18, 'Premium Recorder crafted for artists and performers.', 699, 0, 15, 4.82, 41, 24, 'YTR-2330', 'YAM-YTR2330-TR', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (35, 'Trombone', 'trombone', 1, 4, 19, 'Premium Trombone crafted for artists and performers.', 589, 0, 22, 4.71, 63, 24, 'YCL-250', 'YAM-YCL250-CL', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (37, 'Bugle', 'bugle', 2, 4, 21, 'Premium Bugle crafted for artists and performers.', 19.99, 0, 200, 4.64, 450, 12, 'BLUES-DELUXE', 'FEN-BLU-DLX-BB', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (38, 'Harmonica', 'harmonica', 1, 4, 17, 'Premium Harmonica crafted for artists and performers.', 1149, 10, 8, 4.86, 29, 24, 'YFL-372', 'YAM-YFL372-FL', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (39, 'euphonium', 'euphonium', 1, 4, 18, 'Premium euphonium crafted for artists and performers.', 1399, 0, 6, 4.8, 18, 24, 'YTR-4335GSII', 'YAM-YTR4335-TR', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (40, 'Trumpet', 'trumpet', 1, 4, 19, 'Premium Trumpet crafted for artists and performers.', 1299, 0, 9, 4.91, 33, 36, 'YCL-450', 'YAM-YCL450-CL', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (42, 'Tuba', 'tuba', 2, 4, 21, 'Premium Tuba crafted for artists and performers.', 39.99, 10, 100, 4.7, 142, 12, 'MIDNIGHT-SPECIAL', 'FEN-MID-SPL-C', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (101, 'Banjo', 'banjo', 1, 1, 2, 'Premium Banjo crafted for artists and performers.', 778.31, 10, 11, 4.69, 27, 24, 'FID-242', 'MEL-STR-FID-101', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (102, 'Ukulele', 'ukulele', 2, 1, 5, 'Premium Ukulele crafted for artists and performers.', 274.99, 0, 8, 4.85, 60, 12, 'LUT-758', 'MEL-STR-LUT-102', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (103, 'Harp', 'harp', 2, 1, 5, 'Premium Harp crafted for artists and performers.', 393.34, 0, 23, 4.93, 68, 24, 'OUD-674', 'MEL-STR-OUD-103', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (104, 'Classic Guitar', 'classic-guitar', 2, 1, 2, 'Premium Classic Guitar crafted for artists and performers.', 300.89, 0, 5, 4.91, 65, 12, 'ERH-889', 'MEL-STR-ERH-104', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (105, 'Electric Guitar', 'electric-guitar', 1, 1, 5, 'Premium Electric Guitar crafted for artists and performers.', 804.52, 10, 23, 4.72, 38, 12, 'SAN-689', 'MEL-STR-SAN-105', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (106, 'Acoustic Guitar', 'acoustic-guitar', 2, 1, 5, 'Premium Acoustic Guitar crafted for artists and performers.', 431.06, 0, 5, 4.9, 15, 12, 'TAN-628', 'MEL-STR-TAN-106', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (107, 'Double Bass', 'double-bass', 1, 1, 5, 'Premium Double Bass crafted for artists and performers.', 433.07, 0, 12, 4.54, 19, 12, 'VEE-889', 'MEL-STR-VEE-107', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (108, 'cello', 'cello', 2, 1, 5, 'Premium cello crafted for artists and performers.', 716.51, 0, 14, 4.73, 42, 24, 'SAR-655', 'MEL-STR-SAR-108', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (110, 'violin', 'violin', 2, 1, 3, 'Premium violin crafted for artists and performers.', 848.7, 10, 7, 4.7, 79, 24, 'BAN-236', 'MEL-STR-BAN-110', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (113, 'Harpsichord', 'harpsichord', 3, 2, 10, 'Premium Harpsichord crafted for artists and performers.', 330.66, 10, 17, 4.83, 58, 24, 'CON-264', 'MEL-KEY-CON-113', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (114, 'Accordion', 'accordion', 3, 2, 10, 'Premium Accordion crafted for artists and performers.', 858.14, 10, 7, 4.81, 85, 24, 'ELE-811', 'MEL-KEY-ELE-114', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (116, 'Pipe Organ', 'pipe-organ', 3, 2, 10, 'Premium Pipe Organ crafted for artists and performers.', 197.86, 10, 24, 4.53, 19, 12, 'MID-388', 'MEL-KEY-MID-116', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (117, 'Electronic Keyboard', 'electronic-keyboard', 3, 2, 10, 'Premium Electronic Keyboard crafted for artists and performers.', 99.26, 10, 11, 4.63, 29, 24, 'CEL-315', 'MEL-KEY-CEL-117', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (119, 'Upright Piano', 'upright-piano', 3, 2, 10, 'Premium Upright Piano crafted for artists and performers.', 406.81, 0, 9, 4.72, 64, 12, 'HAR-489', 'MEL-KEY-HAR-119', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (120, 'Grand Piono', 'grand-piono', 3, 2, 10, 'Premium Grand Piono crafted for artists and performers.', 370.45, 0, 16, 4.53, 84, 24, 'ACC-314', 'MEL-KEY-ACC-120', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (121, 'cajon', 'cajon', 3, 3, 12, 'Premium cajon crafted for artists and performers.', 123.31, 0, 13, 4.57, 34, 24, 'TIM-695', 'MEL-PER-TIM-121', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (123, 'Tabla', 'tabla', 3, 3, 12, 'Premium Tabla crafted for artists and performers.', 736.31, 0, 9, 4.66, 24, 12, 'MAR-199', 'MEL-PER-MAR-123', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (124, 'Djembe', 'djembe', 3, 3, 12, 'Premium Djembe crafted for artists and performers.', 804.12, 0, 25, 4.51, 31, 24, 'XYL-690', 'MEL-PER-XYL-124', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (125, 'Bango', 'bango', 3, 3, 12, 'Premium Bango crafted for artists and performers.', 341.3, 0, 16, 4.87, 43, 12, 'COW-863', 'MEL-PER-COW-125', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (126, 'Congo Drum', 'congo-drum', 3, 3, 12, 'Premium Congo Drum crafted for artists and performers.', 472.49, 0, 27, 4.91, 68, 24, 'CLA-204', 'MEL-PER-CLA-126', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (127, 'Tom Tom Drum', 'tom-tom-drum', 3, 3, 12, 'Premium Tom Tom Drum crafted for artists and performers.', 121.24, 0, 17, 4.9, 44, 24, 'CAS-168', 'MEL-PER-CAS-127', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (128, 'Bass Drum', 'bass-drum', 3, 3, 12, 'Premium Bass Drum crafted for artists and performers.', 884.15, 0, 19, 4.72, 31, 24, 'MAR-524', 'MEL-PER-MAR-128', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (131, 'English Horn (Cor Anglais)', 'english-horn-cor-anglais', 1, 4, 21, 'Premium English Horn (Cor Anglais) crafted for artists and performers.', 276.21, 10, 26, 4.82, 54, 12, 'BAS-138', 'MEL-WIN-BAS-131', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (132, 'Cornet', 'cornet', 1, 4, 17, 'Premium Cornet crafted for artists and performers.', 574.25, 0, 25, 4.87, 83, 12, 'REC-122', 'MEL-WIN-REC-132', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (133, 'Saxophone', 'saxophone', 1, 4, 18, 'Premium Saxophone crafted for artists and performers.', 231.25, 10, 28, 4.52, 28, 24, 'TRO-390', 'MEL-WIN-TRO-133', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (136, 'Bass Clarinet', 'bass-clarinet', 1, 4, 18, 'Premium Bass Clarinet crafted for artists and performers.', 184.15, 10, 23, 4.57, 71, 24, 'EUP-219', 'MEL-WIN-EUP-136', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (137, 'shehnai', 'shehnai', 1, 4, 18, 'Premium shehnai crafted for artists and performers.', 114.12, 0, 16, 4.84, 32, 24, 'FRE-523', 'MEL-WIN-FRE-137', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (138, 'Flute', 'flute', 1, 4, 18, 'Premium Flute crafted for artists and performers.', 563.95, 10, 29, 4.56, 19, 24, 'TUB-687', 'MEL-WIN-TUB-138', NOW(), NOW());
INSERT INTO `products` (`id`, `name`, `slug`, `brand_id`, `category_id`, `sub_category_id`, `description`, `price`, `discount_percentage`, `stock_quantity`, `rating`, `review_count`, `warranty_months`, `model_number`, `sku`, `created_at`, `updated_at`) VALUES (140, 'Piccolo', 'piccolo', 1, 4, 18, 'Premium Piccolo crafted for artists and performers.', 367.82, 0, 20, 4.71, 56, 12, 'COR-392', 'MEL-WIN-COR-140', NOW(), NOW());

-- 5. Seed product_images
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (1, 'https://ik.imagekit.io/kmox85pel/Fiddle%20(a%20violin%20used%20in%20folk%20music).webp', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (6, 'https://ik.imagekit.io/kmox85pel/Lute.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (7, 'https://ik.imagekit.io/kmox85pel/Oud.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (8, 'https://ik.imagekit.io/kmox85pel/Erhu.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (9, 'https://ik.imagekit.io/kmox85pel/Santoor.webp', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (10, 'https://ik.imagekit.io/kmox85pel/Tanpura.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (11, 'https://ik.imagekit.io/kmox85pel/Veena.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (12, 'https://ik.imagekit.io/kmox85pel/Sarod.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (13, 'https://ik.imagekit.io/kmox85pel/sitar.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (14, 'https://ik.imagekit.io/kmox85pel/Mandolin.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (2, 'https://ik.imagekit.io/kmox85pel/Stage%20Piano.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (15, 'https://ik.imagekit.io/kmox85pel/Toy%20Piano.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (16, 'https://ik.imagekit.io/kmox85pel/Spinet%20Piano.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (17, 'https://ik.imagekit.io/kmox85pel/Concert%20Organ.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (18, 'https://ik.imagekit.io/kmox85pel/Portable%20Keyboard.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (19, 'https://ik.imagekit.io/kmox85pel/Arranger%20Keyboard.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (20, 'https://ik.imagekit.io/kmox85pel/Electric%20Piano%20(Rhodes).jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (21, 'https://ik.imagekit.io/kmox85pel/Melodica.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (22, 'https://ik.imagekit.io/kmox85pel/MIDI%20Keyboard%20Controller.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (23, 'https://ik.imagekit.io/kmox85pel/Synthesizer.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (3, 'https://ik.imagekit.io/kmox85pel/Timpani(kettle%20drum).jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (24, 'https://ik.imagekit.io/kmox85pel/Vibraphone.webp', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (25, 'https://ik.imagekit.io/kmox85pel/Marimba.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (26, 'https://ik.imagekit.io/kmox85pel/Xylophone.webp', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (27, 'https://ik.imagekit.io/kmox85pel/Cowbell.avif', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (28, 'https://ik.imagekit.io/kmox85pel/Claves.webp', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (29, 'https://ik.imagekit.io/kmox85pel/Castanet.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (30, 'https://ik.imagekit.io/kmox85pel/Maracas.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (31, 'https://ik.imagekit.io/kmox85pel/Triangle.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (32, 'https://ik.imagekit.io/kmox85pel/Tambourine.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (33, 'https://ik.imagekit.io/kmox85pel/wind%20wood/Bassoon.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (34, 'https://ik.imagekit.io/kmox85pel/wind%20wood/Recorder.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (35, 'https://ik.imagekit.io/kmox85pel/wind%20wood/Trombone.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (36, 'https://ik.imagekit.io/kmox85pel/wind%20wood/Pan%20Flute.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (37, 'https://ik.imagekit.io/kmox85pel/wind%20wood/Bugle.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (38, 'https://ik.imagekit.io/kmox85pel/wind%20wood/Harmonica.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (39, 'https://ik.imagekit.io/kmox85pel/wind%20wood/eupho.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (40, 'https://ik.imagekit.io/kmox85pel/wind%20wood/Trumpet.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (41, 'https://ik.imagekit.io/kmox85pel/wind%20wood/French%20Horn.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (42, 'https://ik.imagekit.io/kmox85pel/wind%20wood/Tuba.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (101, 'https://ik.imagekit.io/kmox85pel/Banjo.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (102, 'https://ik.imagekit.io/kmox85pel/Ukulele.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (103, 'https://ik.imagekit.io/kmox85pel/Harp.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (104, 'https://ik.imagekit.io/kmox85pel/Classical%20Guitar.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (105, 'https://ik.imagekit.io/kmox85pel/Electric%20Guitar.avif', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (106, 'https://ik.imagekit.io/kmox85pel/Acoustic%20Guitar.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (107, 'https://ik.imagekit.io/kmox85pel/double-bass.webp', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (108, 'https://ik.imagekit.io/kmox85pel/Cello.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (109, 'https://ik.imagekit.io/kmox85pel/Viola.webp', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (110, 'https://ik.imagekit.io/kmox85pel/violin.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (111, 'https://ik.imagekit.io/kmox85pel/Celesta.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (112, 'https://ik.imagekit.io/kmox85pel/Clavichord.webp', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (113, 'https://ik.imagekit.io/kmox85pel/Harpsichord.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (114, 'https://ik.imagekit.io/kmox85pel/accordion.webp', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (115, 'https://ik.imagekit.io/kmox85pel/Harmonium.webp', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (116, 'https://ik.imagekit.io/kmox85pel/Pipe%20Organ.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (117, 'https://ik.imagekit.io/kmox85pel/Electronic%20Keyboard.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (118, 'https://ik.imagekit.io/kmox85pel/Digital%20Piano.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (119, 'https://ik.imagekit.io/kmox85pel/Upright%20Piano.webp', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (120, 'https://ik.imagekit.io/kmox85pel/Grand%20Piano.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (121, 'https://ik.imagekit.io/kmox85pel/cajon.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (122, 'https://ik.imagekit.io/kmox85pel/Mridangam.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (123, 'https://ik.imagekit.io/kmox85pel/Tabla.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (124, 'https://ik.imagekit.io/kmox85pel/Djembe%20brum.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (125, 'https://ik.imagekit.io/kmox85pel/bongo%20drum.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (126, 'https://ik.imagekit.io/kmox85pel/congo%20drum.webp', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (127, 'https://ik.imagekit.io/kmox85pel/tom%20tom%20drum.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (128, 'https://ik.imagekit.io/kmox85pel/bass%20drum.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (129, 'https://ik.imagekit.io/kmox85pel/snare%20drum.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (130, 'https://ik.imagekit.io/kmox85pel/drum%20set.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (131, 'https://ik.imagekit.io/kmox85pel/wind%20wood/English%20Horn%20(Cor%20Anglais).jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (132, 'https://ik.imagekit.io/kmox85pel/wind%20wood/Cornet.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (133, 'https://ik.imagekit.io/kmox85pel/wind%20wood/Saxophone.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (134, 'https://ik.imagekit.io/kmox85pel/wind%20wood/Oboe.jpg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (135, 'https://ik.imagekit.io/kmox85pel/wind%20wood/Bagpipes.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (136, 'https://ik.imagekit.io/kmox85pel/wind%20wood/Bass%20Clarinet.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (137, 'https://ik.imagekit.io/kmox85pel/wind%20wood/Shehnai.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (138, 'https://ik.imagekit.io/kmox85pel/wind%20wood/flute.webp', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (139, 'https://ik.imagekit.io/kmox85pel/wind%20wood/Clarinet.jpeg', 1, 1, NOW());
INSERT INTO `product_images` (`product_id`, `image_url`, `is_primary`, `display_order`, `created_at`) VALUES (140, 'https://ik.imagekit.io/kmox85pel/wind%20wood/Piccolo.jpeg', 1, 1, NOW());

-- 6. Seed product_specifications
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (1, 'Body Material', 'Alder', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (1, 'Neck Material', 'Maple', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (1, 'Scale Length', '25.5 in', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (1, 'Number of Frets', '22', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (1, 'Color', 'Olympic White', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (6, 'Body Type', 'Dreadnought', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (6, 'Top Wood', 'Solid Sitka Spruce', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (6, 'Back & Sides', 'Solid Mahogany', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (6, 'Finish', 'Open-Pore Satin', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (7, 'String Type', 'Nylon', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (7, 'Top Wood', 'Spruce', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (7, 'Fretboard Material', 'Rosewood', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (7, 'Scale Length', '25.56 in', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (8, 'Top Wood', 'Solid Spruce', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (8, 'Back & Sides', 'Nato/Okume', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (8, 'Body Shape', 'Traditional Western', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (9, 'Body', 'Spruce/Maple', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (9, 'Pickup System', 'Piezo Dual pickup (Bridge & Body)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (9, 'Weight', '1.1 lbs', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (10, 'Body Style', 'A-Style', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (10, 'Top Wood', 'Spruce', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (10, 'Back & Sides', 'Mahogany', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (11, 'Size', 'Soprano', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (11, 'Body Material', 'Mahogany', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (11, 'Number of Frets', '16', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (12, 'Body Material', 'Solid Mahogany', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (12, 'Neck Material', '5-piece Maple/Mahogany', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (12, 'Pickups', 'Double Hum-cancelling Ceramic Pickups', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (12, 'Active Electronics', 'Performance EQ active circuit', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (13, 'Scale Length', '30 in (Short Scale)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (13, 'Neck Shape', 'Modern C', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (13, 'Pickups', '1 Split Single-Coil, 1 Single-Coil J-Bass', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (14, 'Resonating Chamber', 'Yes (Hollow Body design)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (14, 'In/Out Connections', 'Headphone out, Aux in, Line out', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (14, 'Power Supply', 'AA battery or AC adapter', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (2, 'Number of Keys', '88', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (2, 'Type of Keys', 'Graded Hammer Standard (GHS) Keyboard', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (2, 'Touch Sensitivity', 'Hard/Medium/Soft/Fixed', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (2, 'Sound Engine', 'Pure CF Sound Engine', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (2, 'Weight', '26 lbs (11.8 kg)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (15, 'Keyboard', '88-key PHA-4 Standard Keyboard with Escapement', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (15, 'Sound Engine', 'SuperNATURAL Piano Sound', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (15, 'Polyphony', '256 voices', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (15, 'Bluetooth Support', 'Yes (Audio & MIDI)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (16, 'Cabinet Style', 'Baby Grand', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (16, 'Sound Modeling', 'Piano Reality Premium Modeling', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (16, 'Keyboard Action', 'Hybrid Grand Keyboard (Wood/Molded)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (16, 'Speakers', '5-speaker Projection Sound system', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (17, 'Piano Type', 'Upright Acoustic', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (17, 'Soundboard', 'Solid Spruce', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (17, 'Height', '48 inches (121 cm)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (17, 'Finish', 'Polished Ebony', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (18, 'Sound Engines', 'V-Piano Technology & SuperNATURAL', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (18, 'Keyboard Action', '88-key PHA-50 Hybrid structure', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (18, 'Control Interface', '9 sliders, 8 encoder knobs with LED rings', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (19, 'Number of Keys', '61', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (19, 'Touch Response', 'Yes (Soft, Medium, Hard, Fixed)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (19, 'Built-in Voices', '622 Voices', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (19, 'Accompaniment Styles', '205 Auto Styles', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (20, 'Keys Type', '61 Box-shape keys with Ivory Feel', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (20, 'Sound Loop Mix', 'Yes (over 12 sets of patterns)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (20, 'Wireless link', 'Bluetooth 4.2', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (21, 'Display', '7-inch color TFT touch screen', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (21, 'Voices Library', '1337 Voices + 56 Drum Kits', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (21, 'Recording', '16-track MIDI recording capacity', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (22, 'Keyboard', '61 keys with velocity sensitivity', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (22, 'Accompaniment', '300 preset styles + user imports', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (22, 'Inputs', 'Mic input with effects, Bluetooth audio', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (23, 'Keyboard', '88-key weighted PHA-4 Standard', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (23, 'Sound Generator', 'ZEN-Core, SuperNATURAL Acoustic/Electric', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (23, 'Interface', 'USB Audio 4x32, 16 RGB pads, color touchscreen', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (3, 'Drum Sound Module', 'TD-17 x 1', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (3, 'Snare Pad', 'PDX-12 x 1 (12-inch double mesh head)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (3, 'Tom Pads', 'PDX-8 x 3 (8-inch double mesh head)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (3, 'Hi-Hat Cymbal', 'VH-10 x 1 (10-inch dual-trigger cymbals)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (24, 'Shell Material', '100% Birch, 6-ply', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (24, 'Configuration', '5-piece shell pack (no cymbals)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (24, 'Hardware Pack', 'Yamaha HW780 included', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (25, 'Shell Material', '6-ply Poplar', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (25, 'Tension Hoops', '1.5mm Triple-Flange Steel', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (25, 'Includes', 'Cymbal stands, Snare stand, Hi-hat stand, Bass pedal', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (26, 'Snare Pad', 'PDX-8 double-mesh pad', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (26, 'Cymbals', 'CY-5 dual-trigger crash/ride pads', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (26, 'Coach Functions', 'Yes (5 modes)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (26, 'Connectivity', 'Bluetooth Audio/MIDI, USB MIDI', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (27, 'Shell Material', 'Aged Siam Oak', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (27, 'Drum Heads', 'Natural Rawhide (11" and 12" heads)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (27, 'Rim Type', 'Comfort Curve rims', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (28, 'Pads', '9 velocity-sensitive pads with LED lights', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (28, 'Memory Capacity', '32 GB internal storage', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (28, 'Audio Outputs', 'Master L/R outputs, 4 direct audio outputs', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (29, 'Bayan Material', 'Heavy Brass, Chrome plated (approx 3kg)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (29, 'Dayan Material', 'Seasoned Sheesham Wood', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (29, 'Accessories', 'Cushion rings, covers, tuning hammer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (30, 'Pads', '10-inch pad with 13 pressure-sensitive segments', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (30, 'Sounds Library', '850 percussion instruments', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (30, 'Effects', 'Realtime D-BEAM controller, multi-effects', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (31, 'Frontplate Material', 'Meranti Wood', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (31, 'Snare System', 'Built-in dual internal wire set', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (31, 'Feet', 'Non-slip rubber feet', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (32, 'Sound Module', 'Built-in, 30 electronic kit presets', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (32, 'Speaker Output', 'Integrated coaxial speaker (3 W)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (32, 'Power Specs', 'AA battery or AC adapter', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (33, 'Key Type', 'Closed-hole keys', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (33, 'Key System', 'Offset G, Undercut tone holes', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (33, 'Finish', 'Nickel-silver plated body', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (34, 'Valves Type', '3 Monel alloy pistons', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (34, 'Bell Diameter', '4-7/8 inches (123 mm)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (34, 'Finish', 'Gold lacquer finish', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (35, 'Body Material', 'Matte ABS Resin', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (35, 'Keys Material', 'Nickel-plated nickel silver', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (35, 'Barrel Length', '65 mm', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (36, 'Key', 'Eb (Alto)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (36, 'Auxiliary Keys', 'High F#, Front F', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (36, 'Thumb Hook', 'Adjustable plastic hook', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (37, 'Key', 'Bb (Diatonic)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (37, 'Holes Count', '10 holes, 20 reeds', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (37, 'Comb Material', 'Molded PVC plastic comb', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (38, 'Headjoint Material', 'Solid Sterling Silver (.925)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (38, 'Key System', 'Open-hole keys, Offset G, Split E mechanism', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (38, 'Footjoint Type', 'C Footjoint', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (39, 'Bell Material', 'Gold Brass, two-piece bell', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (39, 'Bore Size', 'Medium-Large 0.459 in', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (39, 'Valves Material', 'Monel Alloy', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (40, 'Body Material', 'Grenadilla Wood', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (40, 'Keys Finish', 'Silver-plated keys', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (40, 'Thumb Rest', 'Adjustable with strap ring', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (41, 'Neck Type', '62-style neck (improved response)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (41, 'Key Work', 'High F#, Teardrop front F, Low B-C# connection', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (41, 'Engraving', 'Hand-engraved bell details', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (42, 'Key Tuning', 'C (Diatonic)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (42, 'Cover Plate', 'Matte Black Stainless Steel', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (42, 'Reeds Material', 'Phosphor Bronze reeds', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (4, 'Connectivity', 'USB Type-C', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (4, 'Simultaneous I/O', '2 x 2', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (4, 'Number of Preamps', '2 x mic, 2 x instrument', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (4, 'A/D Resolution', '24-bit/192 kHz', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (5, 'Type', 'Dynamic', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (5, 'Polar Pattern', 'Cardioid', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (5, 'Frequency Response', '50Hz - 15kHz', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (5, 'Connector', '3-pin male XLR', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (43, 'Synth Engine', '100% Discrete Analog', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (43, 'Oscillators', '3 Voltage Controlled Oscillators (VCO)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (43, 'Sequencer', '16-step sequencer with parameter locks', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (44, 'Polyphony', '22 voices', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (44, 'Keyboard', '37 keys with velocity sensitivity', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (44, 'Modulation', 'Phase Motion pad, custom LFO routing', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (45, 'Number of Keys', '49 keys', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (45, 'Controllers', 'Pitch bend/Mod lever, D-BEAM controller', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (45, 'Power', 'USB Bus powered', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (46, 'Engine', 'ACB (Analog Circuit Behavior) + sample play', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (46, 'Sample Storage', 'SD card import supported', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (46, 'Out connections', '8 analog outputs, trigger out, MIDI I/O', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (47, 'Simultaneous I/O', '2 x 2', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (47, 'Number of Preamps', '1 Mic, 1 Instrument/Line', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (47, 'Air Mode', 'Yes (adds high-end presence)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (48, 'Simultaneous I/O', '10 x 4', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (48, 'Dynamic Range', '124dB (D/A converter)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (48, 'Expandability', 'ADAT optical input for 8 extra channels', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (49, 'Type', 'Dynamic', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (49, 'Polar Pattern', 'Cardioid', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (49, 'Electromagnetic Shielding', 'Yes (against computer monitor hum)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (49, 'Mounting', 'Integrated yoke mount', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (50, 'Channels', '2 channels, 4 decks control', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (50, 'Drum Kits', 'Built-in TR drum kits (TR-808, TR-909)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (50, 'Interface', 'Midi Out, USB bus powered, 1/4 inch Mic Input', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (101, 'Instrument Type', 'Fiddle', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (101, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (101, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (102, 'Instrument Type', 'Lute', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (102, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (102, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (103, 'Instrument Type', 'Oud', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (103, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (103, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (104, 'Instrument Type', 'Erhu', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (104, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (104, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (105, 'Instrument Type', 'Santoor', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (105, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (105, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (106, 'Instrument Type', 'Tanpura', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (106, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (106, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (107, 'Instrument Type', 'Veena', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (107, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (107, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (108, 'Instrument Type', 'Sarod', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (108, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (108, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (109, 'Instrument Type', 'sitar', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (109, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (109, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (110, 'Instrument Type', 'Banjo', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (110, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (110, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (111, 'Instrument Type', 'Toy Piano', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (111, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (111, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (112, 'Instrument Type', 'Spinet Piano', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (112, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (112, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (113, 'Instrument Type', 'concert Organ', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (113, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (113, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (114, 'Instrument Type', 'Electric Keyboard', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (114, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (114, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (115, 'Instrument Type', 'Melodica', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (115, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (115, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (116, 'Instrument Type', 'MIDI keyboard controller', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (116, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (116, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (117, 'Instrument Type', 'Celesta', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (117, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (117, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (118, 'Instrument Type', 'Clavichord', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (118, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (118, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (119, 'Instrument Type', 'Harpsichord', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (119, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (119, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (120, 'Instrument Type', 'Accordion', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (120, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (120, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (121, 'Instrument Type', 'Timpani(kettle Drum)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (121, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (121, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (122, 'Instrument Type', 'Vibraphone', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (122, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (122, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (123, 'Instrument Type', 'Marimba', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (123, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (123, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (124, 'Instrument Type', 'Xylophone', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (124, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (124, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (125, 'Instrument Type', 'Cowbell', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (125, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (125, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (126, 'Instrument Type', 'Claves', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (126, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (126, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (127, 'Instrument Type', 'Castanet', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (127, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (127, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (128, 'Instrument Type', 'Maracas', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (128, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (128, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (129, 'Instrument Type', 'Triangle', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (129, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (129, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (130, 'Instrument Type', 'Tambourine', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (130, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (130, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (131, 'Instrument Type', 'Basson', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (131, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (131, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (132, 'Instrument Type', 'Recorder', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (132, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (132, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (133, 'Instrument Type', 'Trombone', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (133, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (133, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (134, 'Instrument Type', 'Pan Flute', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (134, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (134, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (135, 'Instrument Type', 'Bugle', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (135, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (135, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (136, 'Instrument Type', 'euphonium', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (136, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (136, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (137, 'Instrument Type', 'French Horn', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (137, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (137, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (138, 'Instrument Type', 'Tuba', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (138, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (138, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (139, 'Instrument Type', 'English Horn (Cor Anglais)', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (139, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (139, 'Finish', 'Natural Lacquer', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (140, 'Instrument Type', 'Cornet', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (140, 'Build Grade', 'Professional', NOW());
INSERT INTO `product_specifications` (`product_id`, `spec_key`, `spec_value`, `created_at`) VALUES (140, 'Finish', 'Natural Lacquer', NOW());
